### PR TITLE
CI testing ZCU102 SMP

### PR DESCRIPTION
**Pull request by axel-h**
Test with: https://github.com/seL4/seL4_projects_libs/pull/124, https://github.com/seL4/camkes-vm/pull/54

actual PR is https://github.com/seL4/seL4_projects_libs/pull/84, but we need some debug infos

testing https://github.com/seL4/ci-actions/pull/327

### CODE REVIEW

**Comment by chrisguikema** [comment]
Can you add this change to really test the multicore changes?

```
diff --git a/apps/Arm/vm_minimal/zcu102/2022_1/devices.camkes b/apps/Arm/vm_minimal/zcu102/2022_1/devices.camkes
index 5450e81..7d64d8e 100644
--- a/apps/Arm/vm_minimal/zcu102/2022_1/devices.camkes
+++ b/apps/Arm/vm_minimal/zcu102/2022_1/devices.camkes
@@ -27,7 +27,8 @@ assembly {
             "initrd_addr" : VAR_STRINGIZE(VM_INITRD_ADDR),
             "kernel_entry_addr" : VAR_STRINGIZE(VM_ENTRY_ADDR),
         };
-        vm0.num_vcpus = 4;
+        vm0.num_vcpus = 2;
+        vm0.pcus = [2, 3];
```

**Comment by axel-h** [comment]
> Sorry, I had a typo in the original diff. It needs to be `pcpus`. I edited it, but you must have caught it before the edit.

Thanks, I should have spotted this instead of blindly copying the block.

**Comment by axel-h** [comment]
Can you add some more debug output, so we can see what happens?

**Comment by chrisguikema** [comment]
Here's a seL4_projects_libs PR that adds some debug statements: https://github.com/seL4/seL4_projects_libs/pull/124

And here is what I get with those debug prints:

```
[    0.051503] smp: Bringing up secondary CPUs ...
handle_psci@psci.c:50 target_cpu: 1
handle_psci@psci.c:53 Null VCPU
handle_psci@psci.c:55 Found free unassigned VCPU
handle_psci@psci.c:57 Started found VCPU
[    0.071825] Detected VIPT I-cache on CPU1
[    0.075670] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.075809] smp: Brought up 1 node, 2 CPUs
```

**Comment by chrisguikema** [comment]
So guess who forgot to change the typo in his own config....

I've replicated the error. Checking into it now.

**Comment by chrisguikema** [comment]
Okay, I see what's happening now:

The PCPU list is 2 and 3. PSCI is trying to enable (what it thinks it) CPU 1, so we search the PCPU list for 1. When that's not found, we error out.

```
handle_psci@psci.c:53 target_cpu: 1
vm_vcpu_for_target_cpu@guest_vm_util.h:51 Finding vcpu for target 1
vm_vcpu_for_target_cpu@guest_vm_util.h:53 vcpu 0: target cpu: 2
vm_vcpu_for_target_cpu@guest_vm_util.h:53 vcpu 1: target cpu: 3
handle_psci@psci.c:56 Null VCPU
handle_psci@psci.c:58 Found free unassigned VCPU: 0
handle_psci@psci.c:63 Failed to start found VCPU
```

**Comment by axel-h** [comment]
This seems the PR: https://github.com/seL4/seL4_projects_libs/pull/85

**Pull request closed without merging**
